//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fornecedores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fornecedor
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string cnpjOuCpf { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public string telefone { get; set; }
        public string rg { get; set; }
        public Nullable<System.DateTime> dataNasc { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
