//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC5_AngularJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int produtoId { get; set; }
        public string descricao { get; set; }
        public Nullable<int> quantidade { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public Nullable<decimal> valor { get; set; }
    }
}
