//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repositorio
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string language { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string full_name { get; set; }
        public string contributors_url { get; set; }
    }
}
