USE [Estudos]
GO

/****** Object:  Table [dbo].[Taxa]    Script Date: 22/08/2018 09:43:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Taxa](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ValorCobrado] [float] NULL,
 CONSTRAINT [PK_Taxa] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


